"""TyRey Intelligence AI engine.

Every generation injects a structured framework from the IP library — the
engine never freeform-prompts. When ANTHROPIC_API_KEY is not configured the
engine runs in demo mode and returns clearly-labeled sample output so the
full product flow stays testable locally.
"""

import logging

from .config import settings
from .frameworks import build_prompt, load_framework
from .llm import get_provider
from .prompts import load_prompt

logger = logging.getLogger("tyrey.ai")

MAX_TOKENS = 8000

# Funnel pack composition per tier (Phase 7 offer structure).
PACK_TIERS: dict[str, dict] = {
    "starter": {
        "label": "Starter Pack",
        "amount": 2900,
        "modules": ["business_plan", "market_analysis"],
    },
    "investor": {
        "label": "Investor Pack",
        "amount": 9900,
        "modules": ["business_plan", "investor_memo", "market_analysis"],
    },
    "founder": {
        "label": "Founder Premium Pack",
        "amount": 19900,
        "modules": [
            "business_plan",
            "investor_memo",
            "market_analysis",
            "business_genome",
            "intelligence_score",
        ],
    },
}


def _demo_output(framework: dict, context: dict[str, str]) -> str:
    sections = "\n\n".join(
        f"## {s['heading']}\n*{s['guidance']}*\n\n(Sample content — connect an "
        f"ANTHROPIC_API_KEY to generate real intelligence.)"
        for s in framework["sections"]
    )
    ctx = ", ".join(f"{k}: {v}" for k, v in context.items() if v)
    return (
        f"# {framework['title']} (DEMO MODE)\n\n"
        f"> **Demo output.** No ANTHROPIC_API_KEY is configured, so this is a "
        f"structural sample of the {framework['title']} deliverable, not real "
        f"analysis.\n>\n> Input received: {ctx}\n\n{sections}"
    )


def _complete(system: str, user: str) -> str:
    return get_provider().complete(system, user, max_tokens=MAX_TOKENS)


def validate_structure(framework: dict, content: str) -> list[str]:
    """AI-quality gate: verify every required framework section is present.

    Returns missing section headings (empty = valid). Deterministic and free —
    no extra model call.
    """
    lower = content.lower()
    return [
        s["heading"]
        for s in framework["sections"]
        if s["heading"].lower() not in lower
    ]


def generate(framework_name: str, context: dict[str, str]) -> str:
    """Run one intelligence module: framework injection -> Claude -> markdown."""
    framework = load_framework(framework_name)
    system, user = build_prompt(framework, context)

    if not settings.ANTHROPIC_API_KEY:
        logger.warning("ANTHROPIC_API_KEY not set — returning demo output for %s", framework_name)
        return _demo_output(framework, context)

    content = _complete(system, user)

    # Quality gate: one corrective retry if required sections are missing.
    missing = validate_structure(framework, content)
    if missing:
        logger.warning("Output for %s missing sections %s — corrective retry", framework_name, missing)
        corrective = (
            user
            + "\n\n"
            + load_prompt("corrective_retry").format(missing=", ".join(missing))
        )
        content = _complete(system, corrective)

    return content


def generate_preview(idea: str, industry: str, stage: str) -> str:
    """Free funnel lead magnet: Intelligence Score + outline of the full pack."""
    framework = load_framework("intelligence_score")
    system, user = build_prompt(
        framework, {"idea": idea, "industry": industry, "stage": stage}
    )
    user += "\n\n" + load_prompt("preview_constraints")

    if not settings.ANTHROPIC_API_KEY:
        return _demo_output(framework, {"idea": idea, "industry": industry, "stage": stage})

    return _complete(system, user)


def generate_pack(tier: str, idea: str, industry: str, stage: str) -> str:
    """Generate the paid funnel deliverable: every module in the tier, combined."""
    spec = PACK_TIERS[tier]
    context = {
        "idea": idea,
        "industry": industry,
        "stage": stage,
        "objective": "Turn this idea into an investor-ready business",
    }
    parts = [
        f"# TyRey Intelligence™ — {spec['label']}",
        "*Generated by TyRey Intelligence. Outputs are planning tools, not "
        "guarantees of business success or financial/legal advice.*",
    ]
    for module in spec["modules"]:
        parts.append(generate(module, context))
    return "\n\n---\n\n".join(parts)


def edit_document(content: str, instruction: str) -> str:
    """Edit-with-AI: revise a deliverable while preserving its framework structure."""
    system = load_prompt("document_editor")
    user = f"DOCUMENT:\n\n{content}\n\nREVISION INSTRUCTION:\n{instruction}"

    if not settings.ANTHROPIC_API_KEY:
        return (
            content
            + f"\n\n> **Demo edit note:** requested revision — \"{instruction}\" "
            "(connect an ANTHROPIC_API_KEY to apply real AI edits)."
        )

    return _complete(system, user)
